BRMed/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="BRMed API",
        default_version="v1",
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls"), name="quotes"),
    path("api/v1/", include("api.urls"), name="api"),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

api/urls.py
from django.urls import path

from .views import QuoteListAPIView

app_name = "api"

urlpatterns = [
    path("quotes/", QuoteListAPIView.as_view(), name="quote-list-api"),
]

quotes/urls.py
from django.urls import path

from quotes.views import ExchangeRatesView

app_name = "quotes"


urlpatterns = [path("", ExchangeRatesView.as_view(), name="index")]

api/models.py
from django.db import models

# Create your models here.

quotes/models.py
import uuid

from django.db import models


class BaseModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Currency(BaseModel):
    symbol = models.CharField(max_length=10)

    def __str__(self):
        return self.symbol


class Quote(BaseModel):
    target_currency = models.ForeignKey(Currency, on_delete=models.CASCADE)
    date = models.DateField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        unique_together = ["target_currency", "date"]

api/views.py
from drf_yasg.utils import swagger_auto_schema
from rest_framework.generics import ListAPIView
from rest_framework.response import Response

from api.serializers import QuoteFilterSerializer, QuoteSerializer
from api.swagger_params import (
    end_date_param,
    limit_param,
    offset_param,
    start_date_param,
    symbol_param,
)
from quotes.models import Quote


class QuoteListAPIView(ListAPIView):
    serializer_class = QuoteSerializer

    @swagger_auto_schema(
        manual_parameters=[
            symbol_param,
            start_date_param,
            end_date_param,
            limit_param,
            offset_param,
        ]
    )
    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        filters_serializer = QuoteFilterSerializer(
            data=self.request.query_params
        )
        filters_serializer.is_valid(raise_exception=True)
        validated_data = filters_serializer.validated_data

        queryset = Quote.objects.all()

        if "symbol" in validated_data:
            queryset = queryset.filter(
                target_currency__symbol=validated_data["symbol"]
            )

        if "start_date" in validated_data:
            queryset = queryset.filter(date__gte=validated_data["start_date"])

        if "end_date" in validated_data:
            queryset = queryset.filter(date__lte=validated_data["end_date"])

        return queryset.order_by("-date")

    def list(self, request, *args, **kwargs):
        initial_response = super(QuoteListAPIView, self).list(
            request, *args, **kwargs
        )

        response_data = {
            "base_currency": "USD",
            "count": initial_response.data["count"],
            "next": initial_response.data["next"],
            "previous": initial_response.data["previous"],
            "results": initial_response.data["results"],
        }

        return Response(response_data)

quotes/views.py
from django.views.generic import TemplateView

from quotes.utils import fetch_currency_quotes, validate_input


class ExchangeRatesView(TemplateView):
    template_name = "quotes/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        start_date = self.request.GET.get("start_date")
        end_date = self.request.GET.get("end_date")
        selected_currency = self.request.GET.get("currency")

        # Validate input
        error_message = validate_input(start_date, end_date, selected_currency)
        if error_message:
            context["error_message"] = error_message
            return context

        # Fetch data
        currency, quotes = fetch_currency_quotes(
            start_date, end_date, selected_currency
        )
        context["symbol"] = currency.symbol if currency else None
        context["quotes"] = quotes
        context["start_date"] = start_date
        context["end_date"] = end_date
        context["selected_currency"] = selected_currency

        return context

quotes/templates/quotes/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Cotações</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>

<body>
    <div class="container mt-5">
        {% if error_message %}
        <div class="alert alert-danger" role="alert">
            {{ error_message }}
        </div>
        {% endif %}

        <h1 class="text-center">Cotação</h1>
        <div class="container col-xl-10 col-xxl-8 px-4 py-5">
            <div class="card">
                <div class="card-header">
                    Instruções
                </div>
                <div class="card-body">
                    <p class="card-text">
                        <ul>
                            <li>Selecione a data inicial, final e a moeda.</li>
                            <li>Depois clique em atualizar gráfico para ver a cotação.</li>
                            <li>O período informado não deve ser superior a 5 dias úteis</li>
                        </ul>

                    </p>
                </div>
            </div>
        </div>

        <div id="calc_ops" class="container col-xl-10 col-xxl-8 px-4 py-5">
            <div class="row align-items-center g-lg-5 py-5">
                <form method="get" action="{% url 'quotes:index' %}" class="row align-items-end">
                    <div class="col">
                        <label for="codigo_acao" class="form-label">Data de início:</label>
                        <input id="start_date" type="date" class="form-control" name="start_date" value="{{ start_date }}" placeholder="Data de início:">
                    </div>
                    <div class="col">
                        <label for="codigo_acao" class="form-label">Data de fim:</label>
                        <input id="end_date" type="date" class="form-control" name="end_date" value="{{ end_date }}" placeholder="Data de fim:">
                    </div>
                    <div class="col">
                        <label class="form-label" for="autoSizingSelect">Moeda:</label>
                        <select name="currency" class="form-select" id="autoSizingSelect">
                            <option value="BRL" {% if "BRL" in selected_currency %}selected{% endif %}>Real</option>
                            <option value="EUR" {% if "EUR" in selected_currency %}selected{% endif %}>Euro</option>
                            <option value="JPY" {% if "JPY" in selected_currency %}selected{% endif %}>Iene</option>
                        </select>
                    </div>
                    <div class="col">
                        <input id="show_quote_btn" type="submit" class="w-100 btn btn-lg btn-primary" value="Atualizar gráfico">
                    </div>
                </form>

                <hr class="border border-primary border-1 opacity-75">

                <div class="row">
                    <div class="col-12">
                        <div id="exchange-rates-chart"></div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://code.highcharts.com/stock/highstock.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var quotes = {{ quotes|safe }};
            var symbol = '{{ symbol }}';
            var data = quotes.map(function (item) {
                return [new Date(item.date).getTime(), item.price];
            });

            Highcharts.stockChart('exchange-rates-chart', {
                rangeSelector: {
                    selected: 1
                },

                title: {
                    text: 'USD Vs ' + symbol
                },

                series: [{
                    name: symbol,
                    data: data,
                    tooltip: {
                        valueDecimals: 2
                    }
                }]
            });
        });
    </script>
</body>

</html>